$('#slide-1').owlCarousel({
    loop:true,
    margin:20,
    nav:false,
    dots:false,
    autoplay:true,
    autoplayTimeout:1000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
});
$('#slide-2').owlCarousel({
    loop:true,
    margin:0,
    nav:false,
    dots:false,
    autoplay:true,
    autoplayTimeout:5000,
    responsive:{
        0:{
            items:5
        },
        600:{
            items:5
        },
        1000:{
            items:5
        }
    }
});
$('#slide-3').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    dots:false,
    // autoplay:true,
    // autoplayTimeout:5000,
    responsive:{
        0:{
            items:5
        },
        600:{
            items:5
        },
        1000:{
            items:5
        }
    }
});
$('#slide-4').owlCarousel({
    loop:true,
    margin:30,
    nav:false,
    dots:false,
    autoplay:false,
    autoplayTimeout:1000,
    responsive:{
        0:{
            items:5
        },
        600:{
            items:5
        },
        1000:{
            items:5
        }
    }
});